dbt_project:
  outputs:
    dev:
      dbname: dwh
      host: postgres_dwh
      pass: postgres
      port: 5432
      schema: dbo
      threads: 4
      type: postgres
      user: postgres
  target: dev
jaffle_shop:
  outputs:
    dev:
      dbname: dwh
      host: postgres_dwh
      pass: postgres
      port: 5432
      schema: dbo
      threads: 4
      type: postgres
      user: postgres
  target: dev
